# Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- { creator: ophyd.sim.motor, name: sim_motor }
- { creator: ophyd.sim.noisy_det, name: sim_det }

apstools.devices.motor_factory.mb_creator:
- name: bs
  class_name: BeamStopStage
  labels: ["baseline"]
  prefix: "17bm:"
  motors:
    x: m21
    y: m22
    z: m24
- name: det
  class_name: DetectorStage
  # labels: ["baseline"]
  prefix: "17bm:"
  motors:
    x: m23
    y: m6
    z: m33
- name: nm
  class_name: MonochromatorControlStage
  labels: ["baseline"]
  prefix: "17bm:"
  motors:
    theta: m44
    twist: m45
    chi: m46
    pitch: m47
    bend: m48
- name: pin
  class_name: PinStage
  labels: ["baseline"]
  prefix: "17bm:"
  motors:
    x: m17
    y: m18
- name: red
  class_name: RedSampleStage
  labels: ["baseline"]
  prefix: "17bm:"
  motors:
    x: m20
    y: m16
- name: sam
  class_name: SampleStage
  # labels: ["baseline"]
  prefix: "17bm:"
  motors:
    x: m10
    y: m11
    r: m12
- name: sample_table
  class_name: SampleTableStage
  labels: ["baseline"]
  prefix: "17bm:"
  motors:
    # Three-motor vertical assembly (always move together)
    utabv: m41
    drtabv: m42
    dltabv: m43
    # Horizontal motors (less integrated)
    utabh: m49
    dtabh: m50

ophyd.scaler.ScalerCH:
- name: scaler1
  prefix: 17bm:scaler1
  labels: ["scalers", "detectors"]

# FIXME: '17bmVimba:Stat1:1:Total_RBV' not found.
# ophyd.EpicsSignalRO:
# - name: xeye1
#   read_pv: 17bmVimba:ROIStat1:1:Total_RBV
#   labels: ["xrayEye1"]

apstools.synApps.Optics2Slit2D_HV:
- name: slit1
  prefix: 17bm:Slit1
  labels: ["slits", "baseline"]
- name: slit2
  prefix: 17bm:Slit2
  labels: ["slits", "baseline"]
- name: slitWB
  prefix: 17bm:SlitWB
  labels: ["slits", "baseline"]

# ----------------------------------------------------
## EXAMPLES OF OTHER DEVICES THAT YOU CAN USE

# Hint: USAXS has a PTC10

# Repositories with pre-built devices:
# https://bcda-aps.github.io/apstools/latest/api/_devices.html
# https://blueskyproject.io/ophyd/user/reference/builtin-devices.html

# ophyd.Signal:
# - name: test
#   value: 50.7
# - name: t2
#   value: 2

# ophyd.EpicsMotor:
# - {name: m1, prefix: gp:m1, labels: ["motor"]}
# - {name: m2, prefix: gp:m2, labels: ["motor"]}
# - {name: m3, prefix: gp:m3, labels: ["motor"]}
# - {name: m4, prefix: gp:m4, labels: ["motor"]}

# ophyd.EpicsSignal:
# - name: usercalc_xmap_filename
#   write_pv: 2xfmS1:userStringCalc1Enable
#   read_pv: 2xfmS1:userStringCalc1Enable
#   labels: ["usercalc"]

# apstools.devices.ad_creator:
#   - name: adsimdet
#     prefix: "ad:"
#     labels: ["area_detector", "detectors"]
#     plugins:
#       - cam:
#           class: apstools.devices.SimDetectorCam_V34
#       - image
#       - pva
#       - hdf1:
#           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
#           read_path_template: "/path/to/bluesky/tmp/"
#           write_path_template: "/path/to/ioc/tmp/"
#       - roi1
#       - stats1
